config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  resources :posts
  resources :groups_users
  resources :statuses
  resources :groups
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  post '/groups/:group_id/users' => 'groups#add_user'
  post '/groups/:group_id/users/:user_id' => 'groups#delete_user'
  delete '/groups/:group.id/users' => 'groups#delete_user'

  get '/chatrooms/:post_id' => 'chatrooms#join'
  post '/chatrooms/:id' => 'chatrooms#destroy'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, presence: :true
  has_many :groups_users, dependent: :destroy
  has_many :users, through: :groups_users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show
    @users = @group.users
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  def add_user
    @user = User.find(params[:user_id].to_i)
    @group = Group.find(params[:group_id].to_i)
    if !@group.users.exists?(@user.id)
      @group.users.append @user 
      redirect_to @group, notice: 'User has been added to group'
    else 
      redirect_to @group
    end
  end

  def delete_user
    @group = Group.find(params[:group_id].to_i)
    if !@group.users.exists?(params[:user_id].to_i)
      redirect_to @group
    else
      @group.users.destroy(params[:user_id].to_i)
      redirect_to @group, notice: 'User has been deleted from group'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_params
      params.require(:group).permit(:name, :info, :user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.info %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @group.info %>
</p>

<% if !@users.empty? %>
  <h1>List of Users</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% if logged_in? %>
  <%= link_to 'Join', :controller => 'groups', :action => 'add_user', :group_id => @group.id, :user_id => current_user.id, method: :post %>
  <%= link_to 'Leave', :controller => 'groups', :action => 'delete_user', :group_id => @group.id, :user_id => current_user.id, method: :delete %>
<% end %>


<br>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>