config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  resources :posts
  resources :groups_users
  resources :statuses
  resources :groups
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  post '/groups/:group_id/users' => 'groups#add_user'
  post '/groups/:group_id/users/:user_id' => 'groups#delete_user'
  delete '/groups/:group.id/users' => 'groups#delete_user'

  get '/chatrooms/:post_id' => 'chatrooms#join'
  post '/chatrooms/:id' => 'chatrooms#destroy'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include BCrypt
  has_many :statuses, dependent: :destroy
  has_many :groups_users, dependent: :destroy
  has_many :groups, through: :groups_users
  has_many :posts, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :email, presence: true

  def password
    @password ||= Password.new(password_hash) unless password_hash.nil?
  end

  def has_session?
    self.session_exists unless self.session_exists.nil?
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @posts = @user.posts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    @user.password = user_params[:password]
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Hi #{@user.name}"
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    if current_user.id == @user.id
      reset_session
    end
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id]) 
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :info)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_area :info, :cols => "40", :rows => "10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <% if logged_in? && current_user.id == user.id %>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

<% if !@user.info.nil? %>
  <p>
    <strong>info:</strong>
    <%= @user.info %>
  </p>
<% end %>

<% if !@posts.empty? %>
  <h2>List of Posts</h2>
<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Content</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <% if logged_in? && @user.id == current_user.id && !post.has_session? %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% if logged_in? && @user.id == current_user.id %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

<%= link_to 'Back', users_path %>