config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  resources :posts
  resources :groups_users
  resources :statuses
  resources :groups
  resources :users
  get 'welcome/index'

  root 'welcome#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  post '/groups/:group_id/users' => 'groups#add_user'
  post '/groups/:group_id/users/:user_id' => 'groups#delete_user'
  delete '/groups/:group.id/users' => 'groups#delete_user'

  get '/chatrooms/:post_id' => 'chatrooms#join'
  post '/chatrooms/:id' => 'chatrooms#destroy'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  

end

app/models/groups_user.rb
class GroupsUser < ActiveRecord::Base
  validates_uniqueness_of :user_id, scope: :group_id
  belongs_to :user
  belongs_to :group
end

app/controllers/groups_users_controller.rb
class GroupsUsersController < ApplicationController
  before_action :set_groups_user, only: [:show, :edit, :update, :destroy]

  # GET /groups_users
  def index
    @groups_users = GroupsUser.all
  end

  # GET /groups_users/1
  def show
  end

  # GET /groups_users/new
  def new
    @groups_user = GroupsUser.new
  end

  # GET /groups_users/1/edit
  def edit
  end

  # POST /groups_users
  def create
    @groups_user = GroupsUser.new(groups_user_params)

    if @groups_user.save
      redirect_to @groups_user, notice: 'Groups user was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups_users/1
  def update
    if @groups_user.update(groups_user_params)
      redirect_to @groups_user, notice: 'Groups user was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups_users/1
  def destroy
    @groups_user.destroy
    redirect_to groups_users_url, notice: 'Groups user was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_groups_user
      @groups_user = GroupsUser.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def groups_user_params
      params[:groups_user]
    end
end

app/helpers/groups_users_helper.rb
module GroupsUsersHelper
end

app/views/groups_users/_form.html.erb
<%= form_for(@groups_user) do |f| %>
  <% if @groups_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@groups_user.errors.count, "error") %> prohibited this groups_user from being saved:</h2>

      <ul>
      <% @groups_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups_users/edit.html.erb
<h1>Editing Groups User</h1>

<%= render 'form' %>

<%= link_to 'Show', @groups_user %> |
<%= link_to 'Back', groups_users_path %>

app/views/groups_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups_users.each do |groups_user| %>
      <tr>
        <td><%= link_to 'Show', groups_user %></td>
        <td><%= link_to 'Edit', edit_groups_user_path(groups_user) %></td>
        <td><%= link_to 'Destroy', groups_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Groups user', new_groups_user_path %>

app/views/groups_users/new.html.erb
<h1>New Groups User</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_users_path %>

app/views/groups_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_groups_user_path(@groups_user) %> |
<%= link_to 'Back', groups_users_path %>